#!/bin/bash

# The files search script of a specified range of sizes.
# Developed by Aleksandr Dubinin (http://dubinin.net)
# 11th of February 2017

# Displaying error messages
if [ ! -d $1 ]; then
    echo "$0: Error opening dir: $1" 1>&2
elif [ ! -r $1 ]; then
    echo "$0: Access error: $1" 1>&2
# Files search
else
    FIND_CMD="find $1 -type f"
    $FIND_CMD -size +$2c -size -$3c -printf "%h, %f, %s\n" 1>$4
    echo "Number of scanned files:"
    $FIND_CMD | wc -l
fi
exit

